import type { Metadata } from "next";
import { Inter, Lora, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";



export const metadata: Metadata = {
  title: "Sushi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" min-h-screen overflow-x-hidden bg-[#FFF1EB]">
      <Header />
        {children}
      </body>
    </html>
  );
}
